spring.datasource.postgres.url=jdbc:postgresql://localhost:5432/star_rules
spring.datasource.postgres.driver-class-name=org.postgresql.Driver
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=chocolatefrog

spring.jpa.postgres.hibernate.ddl-auto=validate
spring.jpa.postgres.show-sql=true