# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./transaction
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# READ ONLY mode
spring.datasource.hikari.connection-init-sql=SET MODE READ_ONLY

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.com.example.stara=DEBUG