spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/star_rules}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:chocolatefrog}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.enabled=true